//
//  MVPApp.swift
//  MVP
//
//  Created by Daniela Caiceros on 29/03/25.
//

import SwiftUI
import SwiftData

@main
struct MVPApp: App {
    let container: ModelContainer
    let autoGenerateData: Bool
    
    init() {
        let schema = Schema([
            QuizItem.self,
            ResponseItem.self,
        ])
        let modelConfiguration = ModelConfiguration(schema: schema, isStoredInMemoryOnly: false)
        
        do {
            container = try ModelContainer(for: schema, configurations: [modelConfiguration])
            autoGenerateData = true
        } catch {
            fatalError("Could not create ModelContainer: \(error)")
        }
    }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .modelContainer(container)
        }
    }
}
